site_name: Infantio

repo_name: Infantio
repo_url: https://github.com/FGA-EPS-2024-2-Infantio

site_url: https://fga-eps-2024-2-infantio.github.io/
use_directory_urls: true

copyright: Copyright &copy; 2024 Infantio

theme:
  name: material
  language: pt
  logo: assets/logo.png
  favicon: assets/logo.png
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: green
      toggle:
        icon: material/brightness-7
        name: Tema escuro

    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: green
      toggle:
        icon: material/brightness-4
        name: Tema claro
  font:
    text: "Inter"
    code: "sans-serif"

  features:
    - tabs
    - navigation.section

extra:
  base_path: /

nav:
  - Sobre o Projeto: index.md
  - Planejamento:
      - Brainstorm: planejamento/brainstorm.md
      - Protótipo e Validação: planejamento/prototipo_validacao.md
      - Base de desenvolvimento: planejamento/base_desenvolvimento.md
      - Formalização: planejamento/formalizacao.md
      - Cronograma: planejamento/cronograma.md
      - Stack Tecnológico: planejamento/stack_tecnologico.md
      - Planejamento de atividades: planejamento/table.md
  - Sprints:
      - Sprint 1: sprints/sprint1.md
      - Sprint 2: sprints/sprint2.md
      - Sprint 3: sprints/sprint3.md
      - Sprint 4: sprints/sprint4.md
  - Artefatos:
      - Roadmap: artefatos/roadmap.md
      - Storymap: artefatos/roadmap.md
      - Prototipos: artefatos/roadmap.md
      - Personas: artefatos/personas.md
      - Requisitos: artefatos/roadmap.md
      - Histórias de usuário: artefatos/roadmap.md
      - Épicos: artefatos/roadmap.md
  - Entregas:
      - MVP: entregas/mvp.md
      - Documento InfraEstrutura: entregas/docInfra.md
